improving updateTool and blockHeight output

diff --git a/tools/blockHeight b/tools/blockHeight
--- a/tools/blockHeight
+++ b/tools/blockHeight
@@ -36,7 +36,9 @@ blockHeight(){
 		echo -e "\n${greenColour}[+]${endColour} ${grayColour}Block height: ${yellowColour}$(tail -n 1 blocks.txt)${endColour}\n"
 		rm blocks.txt
 	else
-		echo -e "\n${redColour}[+] The node isn't running${endColour}\n"
+		echo -e "\n${redColour}[!] Unable to find the last block${endColour}\n"
+		echo -e "${yellowColour}[!]${endColour} ${grayColour}Check that the node is running and run the command again in one minute.${endColour}\n"
+		tput cnorm && exit 1
 	fi
 	tput cnorm && exit 0
 }
